info:
  contact: {}
paths:
  /user:
    get:
      consumes:
      - application/json
      description: 유저 목록을 가져온다.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: 유저를 가져온다.
swagger: "2.0"
